[package]
name = "promf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
log = "0.4.17"
reqwest = { version = "0.11.16", features = ["blocking"] }
